config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 root to: "main#index"
 get "about-us", to: "about#index" , as: :about

 #user
 get "signup", to: "register#new" 
 get "signin" , to: "session#new"
 post "signin" , to: "session#create"
 delete "logout", to: "session#destroy"
 post "signup", to: "register#create"

 #password
 get "password", to: "password#edit" , as: :edit_password
 patch "password", to: "password#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user   # to cuuent.user  not error 
end

app/models/user.rb
require 'mail'
class User < ApplicationRecord
    before_save :downcase_email

  private
    def downcase_email
        self.email = email.downcase
      end
    
    has_secure_password
    validates :email, length: { minimum: 5 },  presence: [true,"email is require"] , format: { with: URI::MailTo::EMAIL_REGEXP , message: "only allows letters"} 
    validates :password, length: {minimum: 5,message:"too short password"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id]
            Current.user =User.find_by(id: session[:user_id])
        end
    end
    def require_logged_in
        message="please login to continue"
redirect_to signin_path , notice:message if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
 def index
   if session[:user_id]
    @user =User.find_by(id: session[:user_id])
   end
 end


end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
before_action :require_logged_in
 def edit
 end

 def update
if Current.user.update(password_params)
redirect_to root_path , alert: "update password success"
else
    render :edit
 end
end

 private
 def password_params
    params.permit(:password)
 end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def new
        # use instance variable to view can access
       @user =User.new
    end
    def create
@user = User.find_by(email: params[:email])
puts @user
if @user
    message ="Tai khoan da ton tai"
    redirect_to signup_path, notice: message
    return false
end
@user =User.create(user_params)
if @user.errors.to_hash.empty? ==false
   
    message =  @user.errors.to_hash[:email] ?  @user.errors.to_hash[:email].join("") : @user.errors.to_hash[:password].join("")
    redirect_to signup_path, notice:message
end

if @user.errors.to_hash.empty? ==true
    message = "Signup success"
    session[:user_id] = @user.id
   return redirect_to root_path , alert:message
  end
    end
def show
    @user = User.find(params[:id])
end
# def update
#     @user = User.find(params[:id])
#   if @user.update(update_params)
#      redirect_to '/events'
#   else
#      flash[:errors] = @user.errors.full_messages
#      redirect_to "/users/#{@user.id}/edit"
#   end
# end


private

def user_params
    params.require(:user).permit(:email,:password)
end
end

app/controllers/session_controller.rb
# class SessionController < ApplicationController
#     #login
#     def create
#   user = User.find_by(email: params[:session][:email].downcase)
#   if user && user.authenticate(params[:session][:password])
#     session[:user_id] = user.id
#     flash[:notice] = "Logged in successfully."
#     redirect_to user
#   else
#     flash.now[:alert] = "There was something wrong with your login details."
#     render 'new'
#   end
# end
# #logout
# def destroy
#   session[:user_id] = nil
#   flash[:notice] = "You have been logged out."
#   redirect_to root_path
# end
# end


class SessionController < ApplicationController
 def destroy
    session[:user_id] = nil
    message = "You have been logoout"
    redirect_to root_path , notice: message
 end
def new
end

 def create
user = User.find_by(email: params[:email])
puts user
# if !!user 
#     puts 1
#    message  ="User not exsist please sign up account"
#    return redirect_to signup_path, notice: message
#  end

 if user.present? && user.authenticate(params[:password])
    message ="Login successfully"
    session[:user_id] = user.id
  return redirect_to root_path , alert: message
 else
    flash[:notice] ="invalid email or password"
    return redirect_to signin_path
 end
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/about/index.html.erb
<h1> about</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<%= javascript_include_tag '/assets/javascripts/application.js', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
 
<%= render partial: "shared/navbar"%>
<%= render partial: "shared/flash"%>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<%= form_with  model: @user ,url: "/login", method: :post do |form| %>
 <%= form.label :email, "Email" %>
  <%= form.text_field :email %>
  <%= form.label :password, "Password" %>
  <%= form.text_field :password %>
  <%= form.submit "Login" %>
<% end %>

app/views/main/index.html.erb
<%if Current.user%>
<button  type="button" class="btn btn-primary">Hello <%=Current.user %></button>
<h1> Welcome to <%=@user.email%></h1>
<%else%>
<h1> Welcome to BLog app</h1>
<%end%>

app/views/password/edit.html.erb
<%= form_with  model: @user ,url: "/password", method: :patch do |form| %>
 
  <%= form.label :password, "Password" %>
  <%= form.text_field :password %>


  <%= form.submit "update password" %>
<% end %>

app/views/register/new.html.erb
<%= form_with  model: @user ,url: "/signup", method: :post do |form| %>
 <%= form.label :email, "Email" %>
  <%= form.text_field :email %>
  <%= form.label :password, "Password" %>
  <%= form.text_field :password %>
  <%= form.submit "Signup" %>
<% end %>

app/views/session/new.html.erb
<%= form_with url: "/signin", method: :post do |form| %>
 <%= form.label :email, "Email" %>
  <%= form.text_field :email %>
  <%= form.label :password, "Password" %>
  <%= form.text_field :password %>
  <%= form.submit "Login" %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>

<div class="alert alert-danger" id ="flash" role="alert">
 <%=flash[:notice]%>
</div>
<% elsif flash[:alert] %>

<div class="alert alert-success"  id ="flash" role="alert">
<%=flash[:alert]%>
</div>
 <% else %>
<% end %>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class ="navbar_brand"> <%= link_to "NavBar", root_path %>  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
     <a class ="navbar_brand"> <%= link_to "Aboutus", about_path %>  </a>
      </li>
      <li class="nav-item dropdown">
        <a class ="navbar_brand"> <%= link_to "Signup", signup_path %>  </a>
      </li>
      <li class="nav-item">
        <a class="nav-link "><%= link_to "login", signin_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link "><%= link_to "Password", edit_password_path %></a>
      </li>
      <% if  session[:user_id]%>
<li class="nav-item">
       <%= button_to 'Logout', logout_path, method: :delete%>
      </li>
      <% end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
   
  </div>
</nav>